SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `app_conference`
-- ----------------------------
DROP TABLE IF EXISTS `app_conference`;
CREATE TABLE `app_conference` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `subtitle` varchar(512) DEFAULT NULL,
  `speakers` varchar(200) DEFAULT NULL, -- For the moment, let's juste store speakers in a text field
  `description` text,
  `room` ENUM('Borg', 'Adams', 'Dijkstra') NOT NULL DEFAULT 'Borg', -- We have 3 rooms in the conference center
  `start` timestamp NOT NULL, -- Date/time of the conference
  `duration` tinyint NOT NULL, -- How long it will last (in seconds)
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Sample data for `app_conference`, taken from https://fahrplan.events.ccc.de/congress/2018/Fahrplan/index.html
-- ----------------------------
INSERT INTO `app_conference` VALUES 
(1,'The Rocky Road to TLS 1.3 and better Internet Encryption',NULL,'Hanno Böck','Since a few months we have a new version of TLS, the most important encryption protocol on the Internet. From the vulnerabilities that created the need of a new TLS version to the challenges of deploying it due to broken devices this talk will give an overview of the new TLS 1.3.\r\n\r\nIn August the new version 1.3 of the Transport Layer Security (TLS) protocol was released. It‘s the result of a process that started over four years ago when it became increasingly clear that previous TLS versions suffered from some major weaknesses.\r\n\r\nIn many ways TLS 1.3 is the biggest step ever done in the history of TLS and its predecessor SSL. While previous TLS versions always tried to retain compatibility and not change too many things, the new version radically removes problematic and insecure constructions like static RSA key exchanges, fragile CBC/HMAC constructions and broken hash functions like MD5 and SHA1.\r\n\r\nAs a bonus TLS 1.3 comes with a reworked handshake that reduces the number of round-trips and thus provides not just more security, but also better performance. If that sounds too good to be true: An optional, even faster mode of TLS 1.3 – the zero round trip or 0RTT mode – makes some security researchers worried, because they fear it introduces new security risks due to replay attacks.\r\n\r\nThough the road to TLS 1.3 was complicated. The Internet is a buggy place and particularly Enterprise devices of all kinds – middleboxes, TLS-terminating servers and TLS-interception devices – slowed down the deployment and finalization of the new encryption protocol. Also some banks thought that TLS 1.3 is too secure for them.\r\n\r\nThe talk will give an overview of the developments that led to TLS 1.3, the major changes it brings, the challenges it had to face and some practical advice for deployment.','Borg','2018-12-27 10:00:00',60),
(2,'Polizeigesetze','Endlich viele neue Gründe zu demonstrieren','Marie Bröckling, Constanze Kurz','Heimatminister Horst Seehofer und seine Amtskollegen in den Ländern erweitern die Rechte der Polizeien und planen ein „Musterpolizeigesetz“. Damit handelten sie sich die größten Proteste gegen Überwachungsvorhaben seit Jahren ein.\r\n\r\nWir geben nicht nur einen Überblick über die zahlreichen Neuregelungen der Polizeigesetze in den Bundesländern, sondern berichten auch aus den Anhörungen in den Landtagen und von den Stellungnahmen. Wir erklären, was in den neuen Gesetzen steht und welche rechtlichen und technischen Grenzüberschreitungen wir zu kritisieren haben.\r\n\r\nUnd wir haben ein paar Forderungen.','Adams','2018-12-27 22:30:00',60),
(3,'Microtargeting und Manipulation','Von Cambridge Analytica zur EU-Wahl','Ingo Dachwitz, Constanze Kurz','Die Möglichkeiten des Microtargetings, aber auch der Desinformation mit Hilfe von Werbeplattformen wie Facebook sind vielfältiger, als man vor dem Cambridge-Analytica-Skandal vielleicht vermutet hätte. Darauf wollen wir auch angesichts der anstehenden Wahlen in Europa einen Blick werfen.\r\n\r\nSeit dem US-Präsidentschaftswahlkampf und dem Brexit-Entscheid sind Details ans Licht gekommen, wie politische Propaganda heute praktisch durchgeführt wird. Was die noch nicht einmal beendeten Untersuchungen bisher ergeben haben, wollen wir zusammenfassen. Denn dass sie mindestens dazu beitrugen, die Wahlergebnisse zu beeinflussen, ist nun nachvollziehbar.\r\n\r\nEntsprechend werden in Brüssel derzeit Gegenmaßnahmen geplant, die die Wahlen zum Europäischen Parlament vor ungebetenen verdeckten Manipulationen schützen sollen. Aber halten sich die zur Wahl Stehenden selber an ihre Forderungen und Vorschläge?','Adams','2018-12-30 11:30:00',40),
(4,'Jahresrückblick des CCC 2018','Refreshing Memories','Linus Neumann, Constanze Kurz, frank, erdgeist, nexus','Biometrische Videoüberwachung, Hausdurchsuchungen, Polizeiaufgabengesetze, Staatstrojaner und ganz viel Cyber: Wir geben einen Überblick über die Themen, die den Chaos Computer Club 2018 beschäftigt haben.\r\n\r\nNeben der Zusammenfassung und der Rückschau auf das vergangene Jahr wollen wir aber auch über zukünftige Projekte und anstehende Diskussionen reden.\r\n','Adams','2018-12-28 11:50:00',127),
(5,'Compromising online accounts by cracking voicemail systems',NULL,'Martin Vigo','Voicemail systems can be compromised by leveraging old weaknesses and top of current technology. The impact goes way beyond having your messages exposed.\r\n\r\nVoicemail systems have been with us since the 80s. They played a big role in the earlier hacking scene and re-reading those zines, articles and tutorials paints an interesting picture. Not much has changed. Not in the technology nor in some of the attack vectors. Can we leverage the last 30 years innovations to compromise voicemail systems? And what is the real impact today of pwning these?\r\n\r\nIn this talk I will cover voicemail systems, it\'s security and how we can use oldskool techniques and new ones on top of current technology to compromise them. I will discuss the impact of gaining unauthorized access to voicemail systems and introduce a new tool that automates the process','Dijkstra','2018-12-27 17:10:00',40),
(6,'Security Nightmares 0x13',NULL,'ron, franck','Was hat sich im letzten Jahr im Bereich IT-Sicherheit getan? Welche neuen Entwicklungen haben sich ergeben? Welche neuen Buzzwords und Trends waren zu sehen?\r\n\r\nWie immer wagen wir den IT-Security-Alptraum-Ausblick auf das Jahr 2019 und darüber hinaus. Denn was wir wirklich wissen wollen, ist ja schließlich: Welche artifiziell intelligenten Poltergeister werden in unseren Geräten herumspuken, welchen Meistern werden sie gehorchen und wie werden wir sie wieder los?','Adams','2018-12-30 15:10:00',60);
